services:
  db:
    image: postgres:17.6-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main
    ports:
      - 54332:5432
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
